// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khzpzjpepdhhrzpjrdhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoenB6anBlcGRoaHJ6cGpyZGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMDY2ODksImV4cCI6MjA1ODg4MjY4OX0.9r_5CvBkxrD2t19OGbG8dm_EgQLtmumxzXnHf61vBmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);